# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodRater' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherFetch
  	pod 'SnapKit'
  	pod 'Kingfisher'
  	pod 'R.swift'
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'RealmSwift'

end
